---
name: on_tuleap_event1
pack: tuleap
description: Sample rule firing on tuleap.event1.
enabled: true
trigger:
    type: tuleap.event1
action:
    ref: tuleap.greet
    parameters:
        greeting: Yo
